## You have been hired by a rookie movie producer to help him decide what type of movies to produce and which actors to cast. You have to back your recommendations based on thorough analysis of the data he shared with you which has the list of 3000 movies and the corresponding details.

## As a data scientist, you have to first explore the data and check its sanity.

## Further, you have to answer the following questions:
1. ### <b> Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.</b>
2. ### <b>This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)? </b>
3. ### <b> Find out the unique genres of movies in this dataset.</b>
4. ### <b> Make a table of all the producers and directors of each movie. Find the top 3 producers who have produced movies with the highest average RoI? </b>
5. ### <b> Which actor has acted in the most number of movies? Deep dive into the movies, genres and profits corresponding to this actor. </b>
6. ### <b>Top 3 directors prefer which actors the most? </b>

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

# Data Exploration

In [3]:
#Import package
import pandas as pd
import numpy as np

In [4]:
path='/content/drive/MyDrive/imdb_data.csv'
imdb_df = pd.read_csv(path)

In [5]:
imdb_df.head(2)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435

In [6]:
imdb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

In [7]:
print(imdb_df.columns)

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

##After reading all Qs. now subsetting out columns necessary for answering the question in order to get proper insights

#### keeping all columns which are non null

In [8]:
columns_to_keep= ['budget', 'genres','original_language', 'original_title','cast', 'crew', 'revenue']

In [9]:
#find all the row indexes for which genres is not null
imdb_df.loc[~imdb_df['genres'].isna(),'genres']

0                          [{'id': 35, 'name': 'Comedy'}]
1       [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
2                           [{'id': 18, 'name': 'Drama'}]
3       [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...
4       [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
                              ...
2995    [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2996    [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...
2997    [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...
2998    [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2999    [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...
Name: genres, Length: 2993, dtype: object

In [10]:
type(imdb_df.loc[0,'cast'])

str

##Converting the string values to proper list and using it on columns --> cast crew genres
## Converting only non null string

In [11]:
def convert_to_list(str):
  return eval(str)

In [12]:
#apply the above function only on non null values in genres column
imdb_df.loc[~imdb_df['genres'].isna(),'genres']= imdb_df.loc[~imdb_df['genres'].isna(),'genres'].apply(convert_to_list)

In [13]:
#apply the above function only on non null values in cast column
imdb_df.loc[~imdb_df['cast'].isna(),'cast']= imdb_df.loc[~imdb_df['cast'].isna(),'cast'].apply(convert_to_list)

In [14]:
#apply the above function only on non null values in crew column
imdb_df.loc[~imdb_df['crew'].isna(),'crew']= imdb_df.loc[~imdb_df['crew'].isna(),'crew'].apply(convert_to_list)

just keeping in mind which column to use

In [15]:
#creating a copy of orginal df
imdb_df_new = imdb_df.copy()

In [16]:
imdb_df_new.head(2)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435

#Q1.Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.

In [17]:
#checking for sanity in budget columns (outliers,vague values etc)
imdb_df_new.describe()
#budget of a movie in general cannot be 0 hence replacing those value with 0

                id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [18]:

imdb_df_new[imdb_df_new['budget']==0].head(3)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
7,8,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,tt0391024,en,Control Room,A chronicle which provides a rare window into ...,1.949044,...,1/15/04,84.0,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Different channels. Different truths.,Control Room,"[{'id': 917, 'name': 'journalism'}, {'id': 163...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe47a69251416c750a0daf', 'de...",2586511
8,9,"[{'id': 256377, 'name': 'The Muppet Collection...",0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0117110,en,Muppet Treasure Island,After telling the story of Flint's last journe...,6.902423,...,2/16/96,100.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Set sail for Muppet mayhem!,Muppet Treasure Island,"[{'id': 2041, 'name': 'island'}, {'id': 4418, ...","[{'cast_id': 1, 'character': 'Long John Silver...","[{'credit_id': '52fe43c89251416c7501deb3', 'de...",34327391

In [19]:
imdb_df_new['budget'].median()

8000000.0

In [20]:
#Replacing extremely low values of budget and revenue column with median values of budget, revenue
budget_median = imdb_df_new['budget'].median()
revenue_median= imdb_df_new['revenue'].median()
imdb_df_new.loc[imdb_df_new['budget']<1000,'budget']= budget_median
imdb_df_new.loc[imdb_df_new['revenue']<1000, 'revenue']= budget_median

In [21]:
imdb_df_new.describe() #now fine

                id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.474467e+07     8.463274   107.856571  6.687785e+07
std     866.169729  3.583254e+07    12.104000    22.086434  1.374629e+08
min       1.000000  2.500000e+03     0.000001     0.000000  1.404000e+03
25%     750.750000  8.000000e+06     4.018053    94.000000  2.947600e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [22]:
imdb_df_new['genres'].isnull().sum()

np.int64(7)

In [81]:
#creating profit and ROI column
imdb_df_new['profit'] = imdb_df_new['revenue'] - imdb_df_new['budget']
imdb_df_new['roi']= 100* (imdb_df_new['profit']/imdb_df_new['budget'])

In [24]:

imdb_df_new.head(2)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit,roi
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,-12.038207
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,137.873588

In [29]:
#maximum profit
max_profit = imdb_df_new['profit'].max()

In [30]:
imdb_df_new[imdb_df_new['profit']==max_profit]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit,roi
1761,1762,"[{'id': 9485, 'name': 'The Fast and the Furiou...",190000000,"[{'id': 28, 'name': 'Action'}]",http://www.furious7.com/,tt2820852,en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,27.275687,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Vengeance Hits Home,Furious 7,"[{'id': 830, 'name': 'car race'}, {'id': 3428,...","[{'cast_id': 17, 'character': 'Dominic Toretto...","[{'credit_id': '52fe4cc8c3a36847f823e681', 'de...",1506249360,1316249360,692.762821

In [82]:
#finding index or row which have the max profit using .idxmax()
#.idxmax()-->> returns the row number(index) for the max value of the column
imdb_df_new['profit'].idxmax()

1761

###The movie which made the highest profit is:

In [32]:
imdb_df_new.loc[imdb_df_new['profit'].idxmax(),'original_title']

'Furious 7'

In [33]:
max_profit_movie_df = imdb_df_new.iloc[imdb_df_new['profit'].idxmax()]

In [34]:

max_profit_movie_df.head()

id                                                                    1762
belongs_to_collection    [{'id': 9485, 'name': 'The Fast and the Furiou...
budget                                                           190000000
genres                                      [{'id': 28, 'name': 'Action'}]
homepage                                          http://www.furious7.com/
Name: 1761, dtype: object

In [35]:
max_profit_movie_df.loc['cast'][0]['name']

'Vin Diesel'

In [36]:
crew_list= max_profit_movie_df.loc['crew']
crew_list[0:3]

[{'credit_id': '52fe4cc8c3a36847f823e681',
  'department': 'Production',
  'gender': 2,
  'id': 12835,
  'job': 'Producer',
  'name': 'Vin Diesel',
  'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e687',
  'department': 'Production',
  'gender': 2,
  'id': 11874,
  'job': 'Producer',
  'name': 'Neal H. Moritz',
  'profile_path': '/cNcsEYmoS4niCz3UkVAA09dUIob.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e68d',
  'department': 'Writing',
  'gender': 2,
  'id': 58191,
  'job': 'Writer',
  'name': 'Chris Morgan',
  'profile_path': '/dUGxIwFBLrSFLImxjeda1krndMO.jpg'}]

### Name of the director and producer of the movie which made highest profit are:

In [37]:
producer_list=[]
director_list=[]
for person in crew_list:
  if person['job']=='Producer':
    producer_list.append(person['name'])
  if person['job']=='Director':
    director_list.append(person['name'])

In [38]:
print(f'PRODUCERS : {producer_list}')
print(f'DIRECTORS : {director_list}')

PRODUCERS : ['Vin Diesel', 'Neal H. Moritz', 'Michael Fottrell', 'Brandon Birtell']
DIRECTORS : ['James Wan']

In [39]:
cast_list =max_profit_movie_df['cast']

In [40]:
cast_list[0:3]

[{'cast_id': 17,
  'character': 'Dominic Toretto',
  'credit_id': '5431dfd10e0a265915002c34',
  'gender': 2,
  'id': 12835,
  'name': 'Vin Diesel',
  'order': 0,
  'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'},
 {'cast_id': 19,
  'character': "Brian O'Conner",
  'credit_id': '5431dfe4c3a3681143002b98',
  'gender': 2,
  'id': 8167,
  'name': 'Paul Walker',
  'order': 1,
  'profile_path': '/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg'},
 {'cast_id': 18,
  'character': 'Hobbs',
  'credit_id': '5431dfdbc3a36831a6004376',
  'gender': 2,
  'id': 18918,
  'name': 'Dwayne Johnson',
  'order': 2,
  'profile_path': '/kuqFzlYMc2IrsOyPznMd1FroeGq.jpg'}]

###Actors in the Highest profit movie

In [41]:
actor_list=[]
for person in cast_list:
  actor_list.append(person['name'])

In [42]:
#actors
print(f'Actors of the movie are :')
actor_list

Actors of the movie are :

['Vin Diesel',
 'Paul Walker',
 'Dwayne Johnson',
 'Michelle Rodriguez',
 'Tyrese Gibson',
 'Ludacris',
 'Jordana Brewster',
 'Djimon Hounsou',
 'Tony Jaa',
 'Ronda Rousey',
 'Nathalie Emmanuel',
 'Kurt Russell',
 'Jason Statham',
 'Sung Kang',
 'Gal Gadot',
 'Lucas Black',
 'Elsa Pataky',
 'Noel Gugliemi',
 'John Brotherton',
 'Luke Evans',
 'Ali Fazal',
 'Miller Kimsey',
 'Charlie Kimsey',
 'Eden Estrella',
 'Gentry White',
 'Iggy Azalea',
 'Jon Lee Brody',
 'Levy Tran',
 'Anna Colwell',
 'Viktor Hernandez',
 'Steve Coulter',
 'Robert Pralgo',
 'Antwan Mills',
 'J.J. Phillips',
 'Jorge Ferragut',
 'Sara Sohn',
 'Benjamin Blankenship',
 'D.J. Hapa',
 'T-Pain',
 'Brian Mahoney',
 'Brittney Alger',
 'Romeo Santos',
 'Jocelin Donahue',
 'Stephanie Langston',
 'Jorge-Luis Pallo',
 'Tego Calder√≥n',
 'Nathalie Kelley',
 'Shad Moss',
 'Don Omar',
 'Klement Tinaj',
 'Caleb Walker',
 'Cody Walker']

####Understanding the groupby function

In [43]:
#kn.groupby('Name')['No.'].mean()

In [44]:
#kn.groupby('Name').count()

#Q2.This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)?

In [45]:
 #we already calculated roi above
 #df['roi'] = 100 * df['profit']/df['budget']

In [46]:
#Using groupby function on movie languages and ROI and finding mean
imdb_df_new.groupby('original_language')['roi'].mean().reset_index().sort_values(by='roi',ascending=False).head(3)

   original_language           roi
18                ko  11304.181188
6                 el   5198.013245
28                sr   1500.000000

In [47]:

print('Language with highest average roi is')
imdb_df_new.groupby('original_language')['roi'].mean().reset_index().sort_values(by='roi',ascending=False).iloc[0,0]

Language with highest average roi is

'ko'

#Q3.Find out the unique genres of movies in this dataset.

In [48]:
#considering only those rows in genres column which have no null values
no_na_genres = imdb_df_new[~imdb_df_new['genres'].isna()]

In [49]:
len(no_na_genres)

2993

In [50]:
no_na_genres.loc[0,'genres']

[{'id': 35, 'name': 'Comedy'}]

In [51]:
no_na_genres.loc[0,'genres'][0]

{'id': 35, 'name': 'Comedy'}

In [52]:
no_na_genres.loc[3,'genres']

[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'name': 'Drama'}]

In [53]:
#create a list of genres and using .iterrow() method to iterate over genres column
# .iterrow() --->> same as enumerate() its compulsory to use it in case of DataFrame
gen_list=[]
for index,row in no_na_genres.iterrows():
  genre = no_na_genres.loc[index,'genres']
  for k in genre:
    gen_list.append(k['name'])

#unique list of genres are:
pd.DataFrame(set(gen_list),columns=['Unique Genres'])

      Unique Genres
0            Comedy
1          Thriller
2             Crime
3            Family
4           Western
5           Foreign
6             Drama
7           History
8       Documentary
9           Mystery
10        Animation
11         TV Movie
12            Music
13              War
14           Action
15          Romance
16  Science Fiction
17          Fantasy
18           Horror
19        Adventure

#Q4.Make a table of all the producers and directors of each movie. Find the top 3 producers who have produced movies with the highest average RoI?

In [54]:
#considering only those rows in crew column which have no null values
no_na_crew = imdb_df_new[~imdb_df_new['crew'].isna()]

In [55]:
no_na_crew.shape

(2984, 25)

In [56]:
#A simple function to extract list of all producers for a given movie_index
def create_producer_list(index):
  movie_index = no_na_crew.iloc[index]
  crew_list= movie_index.loc['crew']
  producer_list=[]
  for elem in crew_list:
     if elem['job']=='Producer':
        producer_list.append(elem['name'])
  return producer_list

In [57]:
create_producer_list(61)

['James Hill']

In [58]:
#A simple function to extract names of all directors for a given movie_index
#each movie has only one director
def create_director(index):
  movie_index = no_na_crew.iloc[index]
  crew_list= movie_index.loc['crew']

  for elem in crew_list:
     if elem['job']=='Director':
        return elem['name']

In [59]:
create_director(61)

'Carol Reed'

In [60]:
#create a empty DataFrame with required Column names in which we will append data later
Table = pd.DataFrame(columns=['Movie Title','Producers','Directors','ROI'])

####appending in Table Df and using Try Except block to bypass error because some values of the crew dictionaries contain float as value

In [61]:
for index,row in no_na_crew.iterrows():

  try:
      Table = Table.append({'Movie Title':no_na_crew.loc[index,'original_title'],'Producers':create_producer_list(index),'Directors':create_director(index),'ROI':no_na_crew.loc[index,'roi']},ignore_index=True)
  except:
    continue

###Table containing columns of Movie Title,its Producers
###,Directors and ROI

In [62]:
Table.head(10)

Empty DataFrame
Columns: [Movie Title, Producers, Directors, ROI]
Index: []

#Q5.Which actor has acted in the most number of movies? Deep dive into the movies, genres and profits corresponding to this actor.

In [63]:
#considering only those rows in cast column which have no null values
no_na_cast = imdb_df_new[~imdb_df_new['cast'].isna()]

In [64]:
no_na_cast.loc[0,'cast'][0]['name']

'Rob Corddry'

In [65]:
actor_list=[]
for index,row in no_na_cast.iterrows():
  for iter in no_na_cast.loc[index,'cast']:
    if type(iter)== dict:
      actor= iter['name']
      actor_list.append(actor)

In [83]:
#creating a  DataFrame with actor list
Actor_Table = pd.DataFrame(actor_list,columns=['Name of Actor'])

In [84]:
Actor_Table.shape

(61811, 1)

In [85]:
Actor_Table.head()

    Name of Actor
0     Rob Corddry
1  Craig Robinson
2      Clark Duke
3      Adam Scott
4     Chevy Chase

In [86]:
#sorting the actors using groupby function
Actor_Table.value_counts().reset_index().head()

       Name of Actor  count
0  Samuel L. Jackson     30
1     Robert De Niro     30
2     Morgan Freeman     27
3       Bruce Willis     25
4     Susan Sarandon     25

###Actors who have done maximum movies are:

In [87]:
print('Samuel L. Jackson and Robert De Niro both have done 30 films')

Samuel L. Jackson and Robert De Niro both have done 30 films

In [88]:

profit1=[]
profit2=[]
movie1=[]
movie2=[]
for index,row in no_na_cast.iterrows():
  for iter in no_na_cast.loc[index,'cast']:
    if type(iter)== dict:
      actor= iter['name']
      if 'Robert De Niro' in actor:
        profit1.append(no_na_cast.loc[index,'profit'])
        movie1.append(no_na_cast.loc[index,'original_title'])




      if 'Samuel L. Jackson' in actor:
        profit2.append(no_na_cast.loc[index,'profit'])
        movie2.append(no_na_cast.loc[index,'original_title'])

In [89]:
#creating a loop to get the genres for Robert and Samuel
gener_r=[]
a=[]
for i in range(len(movie1)):
  for g in no_na_cast.loc[i,'genres']:
    a.append(g['name'])

  gener_r.append(a)
  a=[]

gener_s=[]
b=[]
for i in range(len(movie2)):
  for g in no_na_cast.loc[i,'genres']:
    b.append(g['name'])

  gener_s.append(b)
  b=[]

In [90]:
genr = np.array(gener_r, dtype=object)
gens = np.array(gener_s, dtype=object)

In [91]:
#creating sub dataframe for Robert
mov1= pd.DataFrame(movie1,columns=['Movie Name'])
prof1=pd.DataFrame(profit1,columns=['Movie Profit'])
gen1= pd.DataFrame(genr.flatten(),columns=['Genres'])

In [92]:
Movies_by_Robert=pd.concat([mov1,gen1,prof1],axis=1)

##Movies by Robert De Niro

In [93]:
Movies_by_Robert.sort_values(by='Movie Profit',ascending=False).head()

          Movie Name                                      Genres  Movie Profit
8   Meet the Parents  [Action, Comedy, Music, Family, Adventure]     275444045
16   American Hustle                          [Horror, Thriller]     211171807
10          Sleepers                                     [Drama]     121615285
26      Analyze This           [Crime, Drama, Mystery, Thriller]      96885658
29         Backdraft        [Action, Adventure, Crime, Thriller]      77368585

In [94]:
#creating sub dataframe for Samuel
mov2= pd.DataFrame(movie2,columns=['Movie Name'])
prof2=pd.DataFrame(profit2,columns=['Movie Profit'])
gen2= pd.DataFrame(gens.flatten(),columns=['Genres'])

In [95]:
Movies_by_Samuel=pd.concat([mov1,gen1,prof1],axis=1)

###Movies by Samuel L jackson

In [96]:
Movies_by_Samuel.sort_values(by='Movie Profit',ascending=False).head()

          Movie Name                                      Genres  Movie Profit
8   Meet the Parents  [Action, Comedy, Music, Family, Adventure]     275444045
16   American Hustle                          [Horror, Thriller]     211171807
10          Sleepers                                     [Drama]     121615285
26      Analyze This           [Crime, Drama, Mystery, Thriller]      96885658
29         Backdraft        [Action, Adventure, Crime, Thriller]      77368585

In [97]:
g=[]
each_movie=[]
for i in range(5):
  b=no_na_genres.loc[i,'genres']
  for k in b:
    g.append(k['name'])
#     each_movie.append([g])

#   a=pd.DataFrame((each_movie))
#   each_movie=[]
# #a=pd.DataFrame([[g]])